baseURL: https://ming-sutaruksanon.netlify.app/
languageCode: en-us
title: Ming Sutaruksanon
theme: forty
googleAnalytics: ''
disqusShortname: ''
params: 
  banner:
    buttonText: Are you ready?
    subtitle: |
     -enjoy life right now-
    title: "Hey, I'm Ming"
  blog: {}
  contact: 
    address: 
      - city: London
        country: UK, NW14SN
        street: Park road, Marylebone
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: kochakorn.sut@gmail.com
        title: Email
    enable: yes
    phone:
      - phone: (44) 7780-775738
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404: 
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer: 
    copyright: Ming Sutaruksanon
    enable: yes
    quicklinks:
      - alt: Click here
        text: 'CV/Resume: '
        url: https://rpubs.com/Ming_Sutaruksanon/CV-Resume
    social:
#      - icon: fa-twitter
#       label: Twitter
#        url: https://www.twitter.com
      - icon: fa-facebook
        label: Facebook
        url: https://www.facebook.com/profile.php?id=100000118947239
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com/mmingmg/
      - icon: fa-github
        label: GitHub
        url: https://github.com/MingSutaruksanon
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/kochakorn-sut/
  image: ''
  name: Your name
  navigation:
    button1:
      - name: Get Started
        url: blogs
#    button2:
 #     - name: Log In
 #       url: '#'
    links:
      - name: Home
        url: '#'
      - name: Blogs
        url: blogs
      - name: Biography
        url: blogs/aliquam
      - name: My stock research
        url: blogs/magna
      - name: My macro/industry research
        url: blogs/ipsum
      - name: Code R Studio
        url: blogs/tempus
    menu: Menu
    subtitle: 
    title: Ming Sutaruksanon
  tiles:
    enable: yes
    showcase:
      - image: IMG_2904.jpg
        subtitle: CV/Resume
        title: Biography
        url: blogs/aliquam
      - image: yield_curve3.png
        subtitle: code (RStudio)
        title: Yield curve inversion
        url: blogs/tempus
      - image: Stocks.jpg
        subtitle: under my coverage
        title: My stock research
        url: blogs/magna
      - image: money.JPG
        subtitle: Code (Stata)
        title: My macro/industry Research
        url: blogs/ipsum
#      - image: IMG_3410.jpg
 #       subtitle: Sport & cooking
  #      title: Extra activities
   #     url: blogs/ipsum
#      - image: pic06.jpg
 #       subtitle: 
  #      title: CV
   #     url: blogs/5
  two:
    buttonText: Dive deeper into my world
    enable: yes
    subtitle: "Hi everyone! I was born in Bangkok, Thailand. Now, I am studying a Master of Financial Analysis at London Business School, London, UK. I discover my passion to digest new information, catch on a trend and seek investment opportunities to gain abnormal return. I enjoy swimming and cooking! especially, international food.  "
    title: Kochakorn Sutaruksanon (Ming)
    url: blogs
